name: Upload df_filtered to Google Sheets2

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests pykrx gspread google-auth gspread-dataframe numpy

      - name: Patch pykrx internal file
        run: |
          PYKRX_PATH=$(python -c "import pykrx, os; print(os.path.dirname(pykrx.__file__))")
          echo "pykrx installed at: $PYKRX_PATH"
          cp patch_pykrx/weibo.py $PYKRX_PATH/website/weibo.py
          echo "Patched weibo.py applied."

      - name: Run upload script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SERVICE_ACCOUNT_FILE: ${{ secrets.SERVICE_ACCOUNT_FILE }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python 저평가주분석2.py

